global:
  scrape_interval:    60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval:    15s

    static_configs:
      - targets: ['localhost:9090']

remote_read:
  - url: "http://host.docker.internal:9201/read"
